server:
  port: 8084

spring:
  application:
    name: NOTIFICATION-SERVICE

##eureka config
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://localhost:8761/eureka
#

  config:
    import: configserver:http://localhost:8088