server:
  port: 8081

spring:
  application:
    name: VET-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/pet-clinic
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#eureka config
eureka:
  instance:
    prefer-ip-address: true  # Mikro hizmet, kendini kaydederken IP adresini tercih eder. Yani, Eureka'ya kayıt olduğunda, hizmetin IP adresi (hostname yerine) kullanılır.
  client:
    fetch-registry: true  # Mikro hizmet, Eureka sunucusundan diğer hizmetlerin kayıtlı bilgilerini alır.
    register-with-eureka: true  # ikro hizmet, başlatıldığında kendini Eureka sunucusuna kaydeder.
    service-url:
      defaultZone : http://localhost:8761/eureka # Bu ayar, mikro hizmetin kayıt olacağı ve diğer hizmet bilgilerini alacağı Eureka sunucusunun URL'sini belirtir.
