server:
  port: 8083

spring:
  application:
    name: OWNER-SERVICE


#eureka config
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
